#+TITLE: quick-search
#+AUTHOR: Parikshit Machwe

* Introduction

This is a simple package to search through common sites from within
Emacs using the natvie browser *eww*.

* Usage

Call the interactive function ~qs-do-search~ which takes in two
inputs:
+ the search string (or the region if active)
+ single letter website code mentioned below.

|-----+------------------------|
| Key | Website                |
|-----+------------------------|
| s   | www.stackoverflow.com  |
| S   | www.scikit-learn.org   |
| t   | www.tutorialspoint.com |
| g   | www.github.com         |
| w   | www.wikipedia.com      |
| e   | www.emacswiki.com      |
| E   | www.ergoemacs.org      |
| c   | www.cplusplus.com      |
|-----+------------------------|


It uses standard Google search with the extra keyword ~site:<special
site>~ appended. It opens it in a side window with *eww*.

You could also specify an external browser by setting the variable
~qs-browser~ to the exteral browser command. It will just call this
through ~shell-command~ and append the URL generated.

* Installation 

Please copy the file ~quick_search.el~ and load it in your init file.
